#!/bin/bash

mkdir -p src/storm
wget https://archive.apache.org/dist/storm/apache-storm-1.1.1/apache-storm-1.1.1.zip -P src/storm
if [ $? -ne 0 ]; then echo unable to download; fi
echo Download Completed . . .
