---
name: storm-test

instance_groups:

- name: storm_instance
  azs: [z1]
  vm_type: default
  instances: 1
  persistent_disk: 2048
  stemcell: default
  networks: 
  - name: default
  jobs:
  - name: nimbus
    release: storm
    properties:
      zookeeper_host: 10.244.0.4 
    instances: 1
  - name: ui
    release: storm

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 0
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 32
  serial: false

releases:
- name: storm
  version: latest

